name: Docker Image CI for GHCR

on:
    # push:
    #     branches: [ "main" ]
    workflow_dispatch:

jobs:
    build_and_publish:
        runs-on: ubuntu-latest
        steps:
            # Checkout the repository
            - uses: actions/checkout@v3
            
            # Set up Docker Buildx
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            
            # Log in to GitHub Container Registry (GHCR)
            - name: Log in to GHCR
              run: echo ${{ secrets.GH_PAT }} | docker login --username Core447 --password-stdin ghcr.io
            
            # Build and push the Docker image for arm64/v8
            - name: Build and push Docker image
              run: |
                docker buildx build \
                  --platform linux/arm64/v8 \
                  --push \
                  -t ghcr.io/core447/blockchain-demo:latest .
